on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      run: npm install
      run: node ./scripts/check-tags.js
